language: node_js

node_js:
  - node

cache:
directories:
- node_modules

# language: node_js
# node_js:
# - node
# cache:
#   directories:
#   - node_modules

# before_install:
#   npm update -g npm

