language: node_js

node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"

cache:
directories:
- node_modules

# language: node_js
# node_js:
# - node
# cache:
#   directories:
#   - node_modules

# before_install:
#   npm update -g npm

